# Importar y comprobar acceso a fichero customers.xlsx

In [12]:
import pandas as pd

# Leer el archivo customers.xls
df = pd.read_excel('customers.xlsx')

# Mostrar las primeras filas del DataFrame
df.head()

,customerID,companyName,contactName,contactTitle,address,city,region,postalCode,country,phone,fax,Unnamed: 11
0,ALFKI,Alfreds Futterkiste,Maria Anders,Sales Representative,Lengeder Str. 56,Berlin,NaN,12209,Germany,030-0074321,030-0076545,NaN
1,ANATR,Ana Trujillo Emparedados y helados,Ana Trujillo,Owner,Avda. de la Constitución 2222,Granada,NaN,5021,Mexico,(5) 555-4729,(5) 555-3745,NaN
2,ANTON,Antonio Moreno Taquería,Antonio Moreno,Owner,Mataderos 2312,México D.F.,NaN,5023,Mexico,(5) 555-3932,NaN,NaN
3,AROUT,Around the Horn,Thomas Hardy,Sales Representative,120 Hanover Sq.,London,NaN,WA1 1DP,UK,(171) 555-7788,(171) 555-6750,NaN
4,BERGS,Berglunds snabbköp,Christina Berglund,Order Administrator,Berguvsvägen 8,Sundsvall,NaN,S-958 22,Sweden,0921-12 34 65,0921-12 34 67,NaN

In [14]:
import pandas as pd
import time
from geopy.geocoders import Nominatim

# Leer el archivo customers.xlsx
df = pd.read_excel('customers.xlsx')

# Inicializar el geocodificador de Nominatim
geolocator = Nominatim(user_agent="geo_locator")

def obtener_longitud_latitud(direccion, ciudad):
    try:
        ubicacion = geolocator.geocode(f"{direccion}, {ciudad}")
        if ubicacion:
            return ubicacion.longitude, ubicacion.latitude
        else:
            return "Null", "Null"
    except Exception as e:
        print(f"Error al obtener la ubicación para {direccion}, {ciudad}: {e}")
        return "NonData", "NonData"
    finally:
        # Agregar un retardo de 1 segundo entre las solicitudes
        time.sleep(1)

# Aplicar la función a cada fila del DataFrame
df['longitud'], df['latitud'] = zip(*df.apply(lambda row: obtener_longitud_latitud(row['address'], row['city']), axis=1))

# Crear un nuevo DataFrame con las columnas requeridas
resultados_df = df[['customerID', 'longitud', 'latitud']]

# Guardar el resultado en un nuevo archivo resultados.xls
resultados_df.to_excel('padinpresaResultados.xlsx', index=False)

Error al obtener la ubicación para Rambla de Cataluña 3, Barcelona: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Rambla+de+Catalu%C3%B1a+3%2C+Barcelona&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))